export const COOKING_STEP_MAP_MAX_BODY_BYTES = 128_000
export const COOKING_STEP_MAP_MAX_CONTENT_LENGTH = 64_000
export const COOKING_STEP_MAP_MAX_INGREDIENTS = 200
export const COOKING_STEP_MAP_MAX_INSTRUCTIONS = 150
export const COOKING_STEP_MAP_MAX_LINE_LENGTH = 4_000
